/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraElev;

/**
 *
 * @author carlo
 */
public class CalculadoraElev extends javax.swing.JFrame {
    private boolean escriu;// Si true, està a l'espera d'escriure. Si false, acaba de mostrar el resultat
    private int numeroprevi;
    /**
     * Creates new form NewJFrame
     */
    public CalculadoraElev() {
        initComponents();
        escriu = false;
        pantallaResultat.setText("");
        this.numeroprevi = -1;
        this.setTitle("Calculadora Calvo_L");
        this.setResizable(false);
        exy.setEnabled(true);
        ex2.setEnabled(true);
        botoigual.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b7 = new javax.swing.JButton();
        pantallaResultat = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        ex2 = new javax.swing.JButton();
        botoigual = new javax.swing.JButton();
        exy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b0 = new javax.swing.JButton();
        bCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b7.setForeground(new java.awt.Color(255, 0, 0));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        pantallaResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaResultatActionPerformed(evt);
            }
        });

        b1.setForeground(new java.awt.Color(255, 0, 0));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b4.setForeground(new java.awt.Color(255, 0, 0));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setForeground(new java.awt.Color(255, 0, 0));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b2.setForeground(new java.awt.Color(255, 0, 0));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b5.setForeground(new java.awt.Color(255, 0, 0));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b9.setForeground(new java.awt.Color(255, 0, 0));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b3.setForeground(new java.awt.Color(255, 0, 0));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setForeground(new java.awt.Color(255, 0, 0));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        ex2.setForeground(new java.awt.Color(0, 0, 204));
        ex2.setText("x^2");
        ex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex2ActionPerformed(evt);
            }
        });

        botoigual.setForeground(new java.awt.Color(0, 0, 255));
        botoigual.setText("=");
        botoigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoigualActionPerformed(evt);
            }
        });

        exy.setForeground(new java.awt.Color(0, 0, 204));
        exy.setText("x^y");
        exy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exyActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculadoraElev/Abaco.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        b0.setForeground(new java.awt.Color(255, 0, 0));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bCE.setForeground(new java.awt.Color(0, 0, 255));
        bCE.setText("CE");
        bCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pantallaResultat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b1)
                                    .addComponent(b7)
                                    .addComponent(b4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b2)
                                    .addComponent(b8)
                                    .addComponent(b5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b3)
                                    .addComponent(b9)
                                    .addComponent(b6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ex2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoigual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pantallaResultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(exy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoigual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("9");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("9");
            pantallaResultat.setText(nouText);
            escriu = false;
        }    
            
        
    }//GEN-LAST:event_b9ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("1");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("1");
            pantallaResultat.setText(nouText);
            escriu = false;
        }    
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("2");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("2");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("3");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("3");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("4");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("4");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("5");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("5");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("6");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("6");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("7");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("7");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("8");
            pantallaResultat.setText(nouText);
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("8");
            pantallaResultat.setText(nouText);
            escriu = false;
        }   
    }//GEN-LAST:event_b8ActionPerformed

    private void ex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex2ActionPerformed
        // TODO add your handling code here:
        int cuadrat = Integer.parseInt(pantallaResultat.getText().toString());
        cuadrat = cuadrat * cuadrat;
        pantallaResultat.setText("" + cuadrat +"");
    }//GEN-LAST:event_ex2ActionPerformed

    private void exyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exyActionPerformed
        // TODO add your handling code here:
        if(this.numeroprevi == -1){ //No hi ha numero previ guardat
            if(!pantallaResultat.getText().toString().isEmpty()){
                this.numeroprevi = Integer.parseInt(pantallaResultat.getText().toString());
                escriu = true;
                exy.setEnabled(false);
                ex2.setEnabled(false);
                botoigual.setEnabled(true);
                return;
                
            } else { 
                return;}
            
        } else {
                this.numeroprevi = Integer.parseInt(pantallaResultat.getText().toString());
                escriu = true;
                exy.setEnabled(false);
                ex2.setEnabled(false);
                botoigual.setEnabled(true);
                
        }
        
        
    }//GEN-LAST:event_exyActionPerformed

    private void pantallaResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaResultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaResultatActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if(!escriu){
            String text = pantallaResultat.getText().toString();
            String nouText = text.concat("0");
            pantallaResultat.setText(nouText);
            System.out.println("cami1");
            
        } else { //Si venim de fer clic a un botó
            String text = "";
            String nouText = text.concat("0");
            pantallaResultat.setText(nouText);
            System.out.println("cami2");
            escriu = false;
        }   
    }//GEN-LAST:event_b0ActionPerformed

    private void bCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCEActionPerformed

        exy.setEnabled(true);
        ex2.setEnabled(true);
        botoigual.setEnabled(false);
        escriu = false;
        pantallaResultat.setText("");
        this.numeroprevi = -1;

        
    }//GEN-LAST:event_bCEActionPerformed

    private void botoigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoigualActionPerformed
        // TODO add your handling code here:
        int potencia = Integer.parseInt(pantallaResultat.getText().toString());
        int resultado = (int) Math.pow(this.numeroprevi, potencia);
        this.numeroprevi = resultado;
        escriu = true;
        pantallaResultat.setText("" + resultado +"");
        exy.setEnabled(true);
        ex2.setEnabled(true);
        botoigual.setEnabled(false);
    }//GEN-LAST:event_botoigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                    new CalculadoraElev().setVisible(true);
                }
        });
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bCE;
    private javax.swing.JButton botoigual;
    private javax.swing.JButton ex2;
    private javax.swing.JButton exy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pantallaResultat;
    // End of variables declaration//GEN-END:variables
}
